Pool: {
  shape: class
  Origianl: GameObject
  Root: Transform
  -_poolStack: Stack<Poolable>

  Init(GameObject orginal, int count = 5)
  Create(): Poolable
  Push(Poolable poolable)
  Pop(Transform parent): Poolable
}
