SoundManager: {
  shape: class
  _audioSources: "AudioSource[]"
  _audioClips: Dictionary<string, AudioClip>

  Init()
  Clear()
  Play(string path, Define.Sound type = Define.Sound.Effect, float pitch = 1.0f)
  Play(AudioClip audioClip, Define.Sound type = Define.Sound.Effect, float pitch = 1.0f)
  GetOrAddAudioClip(string path, Define.Sound type = Define.Sound.Effect): AudioClip
}
