BaseController: {
  shape: class
  \#_destPos: Vector3
  \#_state: Define.State
  \#_lockTarget: GameObject
  WorldObjectType: Define.WorldObject
  State: Define.State

  \#Start()
  \#Update()
  Init()
  \#UpdateDie()
  \#UpdateMoving()
  \#UpdateIdle()
  \#UpdateSkill()
  \#OnHitEvent()
}
