PlayerController: {
  shape: class
  -_mask: int
  -_stat: PlayerStat
  -_stopSkill: bool

  Init()
  \#UpdateMoving()
  \#UpdateSkill()
  \#OnHitEvent()

  -OnMouseEvent(Define.MouseEvent evt)
  -OnMouseEvent_IdleRun(Define.MouseEvent evt)
}
