SpawningPool: {
  shape: class
  -_monsterCount: int
  -_reserveCount: int
  -_keepMonsterCount: int
  -_spawnPos: Vector3
  -_spawnRadius: float
  -_spawnTime: float
  AddMonsterCount(int value)
  SetKeepMonsterCount(int count)
  -Start()
  -Update()
  ReserveSpawn(): IEnumerator
}
