Stat: {
  shape: class
  \#_level: int
  \#_hp: int
  \#_maxHp: int
  \#_attack: int
  \#_defense: int
  \#_moveSpeed: int

  Level: int
  HP: int
  MaxHp: int
  Attack: int
  Defense: int
  MoveSpeed: int

  -Start()
  OnAttacked(Stat attacker)
  \#OnDead(Stat attacker)
}
