Util: {
  shape: class
  GetOrAddComponet(GameObject go): T
  FindChild(GameObject go, string name = null, bool recursive = false): GameObject
  FindChild(GameObject go, string name = null, bool recursive = false): T
}
