Managers: {
  shape: class
  s_instance: Managers
  Instance: Managers
  -_game: GameManagerEx
  Game: GameManagerEx
  -_data: DataManager
  -_input: InputManager
  -_pool: PoolManager
  -_resource: ResourceManager
  -_scene: SceneManagerEx
  -_sound: SoundManager
  -_ui: UIManager

  Data: DataManager
  Input: InputManager
  Pool: PoolManager
  Resource: ResourceManager
  Scene: SceneManagerEx
  Sound: SoundManager
  UI: UIManager

  Start()
  Update()
  Init()
  Clear()
}
