UI_Base: {
  shape: class
  \#_objects: "Dictionary<Type, UnityEngine.Object[]>"
  Init()
  -Start()

  \#Bind(Type type)
  \#Get(int idx)

  \#GetObject(int idx): GameObject
  \#GetText(int idx): Text
  \#GetButton(int idx): Button
  \#GetImage(int idx): Image

  BindEvent()
}
