UI_EventHandler: {
  shape: class
  OnBeginDragHandler: Action<PointerEventData>
  OnDragHandler: Action<PointerEventData>
  OnClickHandler: Action<PointerEventData>

  OnBeginDrag(PointerEventData eventData)
  OnDrag(PointerEventData eventData)
  OnPointerClick(PointerEventData eventData)
}
