GameManagerEx: {
  shape: class
  -_player: GameObject
  -_monsters: HashSet<GameObject>
  OnSpawnEvent: Action<int>
  GetPlayer(): GameObject

  Spawn(Define.WorldObject type, string path, Transform parent = null): GameObject
  GetWorldObjectType(GameObject go): Define.WorldObject
  Despawn(GameObject go)
}
